# Generated by Django 5.0.4 on 2025-05-15 06:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building_num', models.IntegerField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('house_num', models.CharField(blank=True, max_length=8, null=True)),
                ('post_num', models.IntegerField(blank=True, null=True)),
                ('post_name', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25830)),
            ],
        ),
    ]
