# Generated by Django 5.0.4 on 2025-05-02 05:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parc_st', models.CharField(blank=True, max_length=100, null=True)),
                ('sifko', models.IntegerField(max_length=4)),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25830)),
            ],
        ),
        migrations.CreateModel(
            name='parcels_Owners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
