# Generated by Django 5.0.4 on 2025-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_alter_parcels_sifko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='parc_st',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
