# Generated by Django 5.0.4 on 2025-05-15 06:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('str_name', models.CharField(blank=True, max_length=100, null=True)),
                ('administrator', models.CharField(blank=True, max_length=64, null=True)),
                ('maintainer', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=25830)),
            ],
        ),
    ]
