# Generated by Django 5.0.4 on 2025-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roads',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
